### ISSUE TITLE
Config file to disable kill notifications

### ISSUE THREAD

**Issue by Hardeh** [Swaggies/BetterEXP#1]
I know it can be disabled from chat, but i suggest adding config file, so we can preconfigure turning off this feature into the modpack.
I really think that this feature is a spoiler, which can ruin part of the fun from the game. You don't supposed to know what's happening if you're not there.

**Comment by Swaggies** [comment]
config file will be added with other settings you can tweak in 1.2.0 (eta about sunday or monday)

**Comment by Swaggies** [comment]
done in 1.1.2
