### ISSUE TITLE
[Feature Requests] Configurable Performance Report

### ISSUE THREAD

**Issue by Mari0no1** [Swaggies/BetterEXP#10]
Here are two feature I suggest you to add to your mod : 

1. Be able to change the color of the different new stats shown via the config file. (For me, this would be to put them all red so it fits more with the vanilla report)

2. Choose which new stats are shown in the performance report via th config file. (An option to enable or disable each one of them)

The first one being the biggest reason I don't add the mod to my modpack as I don't like everything being all colorful.
Best regards. Thanks for listening

**Comment by Swaggies** [comment]
i actually had plans for this! ill try to get this out by tomorrow or monday by the absolute latest.

**Comment by Swaggies** [comment]
closing since i added this in 2.1, feel free to reopen if you have any more requests

**Comment by Mari0no1** [comment]
Hello, I do have another request
I would like an option to make the text red like vanilla does it instead of pink
