### ISSUE TITLE
[Compatibility] AdvancedCompany Performance Report

### ISSUE THREAD

**Issue by YoBii** [Swaggies/BetterEXP#5]
Thank you for the update. I love that we can have your mod together with Coroner Funny notes now. 

However there's a minor issue that has been introduced with the _collected_ stat when also using AdvancedCompany. 

It has its own performance report screen and will end up looking like this

![image](https://github.com/Swaggies/BetterEXP/assets/22051355/fc0cffd9-03b5-4be7-bafb-d8a0bb3898e9)

A config toggle for compatibilities sake would suffice, maybe there's even a way you can make it fit idk.

**Comment by YoBii** [comment]
When player died:
![image](https://github.com/Swaggies/BetterEXP/assets/22051355/c29cd824-69d4-464c-b7bf-3741a72e1063)

**Comment by Swaggies** [comment]
option to change the position of it added in 1.2.1.

**Comment by Hardeh** [comment]
Eh, there's nothing new in 1.2.1 besides version change?

**Comment by YoBii** [comment]
Can confirm. No new config option.

**Comment by Swaggies** [comment]
thunderstore release should be fixed now.
