### ISSUE TITLE
Issue of EXP decrementing not related to BetterEXP

### ISSUE THREAD

**Issue by Keaft** [Swaggies/BetterEXP#7]
Hey so this is actually not an issue with BetterEXP and in fact I was looking into BetterEXP as a potential solution as your mod seemed like a dang cool option for EXP in general.

I'm running into an issue of EXP only seeming to decrement with my modpack: https://thunderstore.io/c/lethal-company/p/ThePathfinders/The_Pathfinders_Modpack/

I recognize fully that you have no dog in the fight here and don't expect you to take this issue but figured you might have some insights with your work on BetterEXP. I attempted to throw BetterEXP into the mix to see if it could overwrite whatever may be causing EXP to only go down to no avail. After having read through your documentation and other issues it sounds like BetterEXP piggybacks off the vanilla system which I find to be a pretty elegant solution for maintaining a player's progress across whatever mod list they choose.

AdvancedCompany, GeneralImprovements, and LCBetterSaves to my unlearned eye seem to be the mods in the list that have the potential of changing the vanilla EXP mechanics the most, but I've exhausted the avenues of research which is why I'm here looking for at least an insight or ideas for further pursuit.

Thanks for taking the time to read! 😄 Feel free to close this!

**Comment by Swaggies** [comment]
since its not an issue abt betterexp directly ill close it here, but youre welcome to contact me on discord (swaggies) and id be happy to help!
