### ISSUE TITLE
Not client side anymore?

### ISSUE THREAD

**Issue by Dsnherdude066** [Swaggies/BetterEXP#8]
so ive got this only client side thunder profile and it was working before the update now after the update it doesn't work at all, i tryed to down grade Bexp and it still doesnt work

I was playing in a public lobbys right before the update so i know it was Bexp

**Comment by Swaggies** [comment]
betterexp is still client-sided. i havent modified anything that would change that.

**Comment by Swaggies** [comment]
closing since this is cold now and betterexp doesnt have anything that would make it not client-sided
